#! /bin/bash -e
# Mimics addpkg behavior in git.

case `uname` in
  Darwin)
    ECHO="echo" ;;
  *)
    ECHO="echo -e" ;;
esac

usage () {
  COMMAND_NAME=$1
  $ECHO "git $COMMAND_NAME [options] Subsystem/Package [Subsystem/Package ...] "
  $ECHO "git $COMMAND_NAME [options] -f FILE"
  $ECHO
  $ECHO "Options:"
  $ECHO "-h                 \tthis help message"
  $ECHO
  $ECHO "-d, --debug        \tenable debug output"
  $ECHO "-f, --file FILE    \tread the list of packages to be checkoed out from FILE"
  $ECHO "-q, --quiet, -z    \tdo not print out progress"
  if [ "$COMMAND_NAME" == "cms-addpkg" ]; then
    $ECHO "    --https        \tuse https, rather than ssh to access your personal repository"
    $ECHO "    --ssh          \tuse ssh, rather than https to access the official repository"
    $ECHO "-y, --yes          \tassume yes to all questions"
  fi
  exit $2
}

checkPkgFile () {
  INPUT_FILE="$1"
  CURRENT_BRANCH="$2"
  for PKG_NAME in `cat $INPUT_FILE`; do
    if [ ! -d "$CMSSW_BASE/src/$PKG_NAME" ]; then
      [ "$HEADER" ] || { $ECHO "\nThese packages do not exist in branch $CURRENT_BRANCH"; HEADER=done; }
      echo $PKG_NAME
    fi
  done
  if [ "$HEADER" ]; then
    exit 1
  fi
}

checkPkgList () {
  PACKAGES="$1"
  CURRENT_BRANCH="$2"
  for PKG_NAME in $PACKAGES; do
    if [ ! -d "$CMSSW_BASE/src/$PKG_NAME" ]; then
      [ "$HEADER" ] || { $ECHO "\nThese packages do not exist in branch $CURRENT_BRANCH"; HEADER=done; }
      echo $PKG_NAME
    fi
  done
  if [ "$HEADER" ]; then
    exit 1
  fi
}

COMMAND_NAME=$(basename $0 | sed -e's/^git-//')
ACTION="Checking out"
if [ "$COMMAND_NAME" = "cms-rmpkg" ]; then
  RMPKG=true
  ACTION="Removing"
fi

DEBUG=0
VERBOSE=1
INITOPTIONS=""                      # options passed to git cms-init
PACKAGES=
INPUT_FILE=

# colors and formatting
RED='\033[31m'
NORMAL='\033[0m'

verbose () {
  if [ "X$VERBOSE" = X1 ]; then
    echo "$@"
  fi
}

while [ "$#" != 0 ]; do
  case "$1" in
    -h | --help )
      usage $COMMAND_NAME 0;;
    -d | --debug )
      INITOPTIONS="$INITOPTIONS $1"
      shift; set -x; DEBUG=1 ;;
    -f | --file )
      OPTION=$1; shift
      INPUT_FILE="$1"; shift
      if [ ! "$INPUT_FILE" ]; then
        $ECHO "git cms-addpkg: option $OPTION requires an argument"
        $ECHO
        usage 1
      elif [ ! -r "$INPUT_FILE" ]; then
        $ECHO "git cms-addpkg: file $INPUT_FILE does not exist or is not readable"
        $ECHO
        usage $COMMAND_NAME 1
      fi
      unset OPTION
      ;;
    -q | --quiet | -z )
      INITOPTIONS="$INITOPTIONS $1"
      shift; set +x; DEBUG=0; VERBOSE=0 ;;
    -y | --yes )
      INITOPTIONS="$INITOPTIONS $1"
      shift;;
    --https )
      INITOPTIONS="$INITOPTIONS $1"
      shift;;
    --ssh )
      INITOPTIONS="$INITOPTIONS $1"
      shift;;
    -*)
      $ECHO "git cms-addpkg: unknown option $1"; $ECHO; usage $COMMAND_NAME 1;;
    *)
      if [ "$INPUT_FILE" == "" ]; then
        # check out a list of packages
        PACKAGES="$PACKAGES $1"
        shift
      else
        # check out a list of packages via -f / --file FILE
        $ECHO "git $COMMAND_NAME: you cannot specify a package and input from file at the same time."
        $ECHO
        usage $COMMAND_NAME 1
      fi
    ;;
  esac
done
if [ "$PACKAGES" == "" ] && [ "$INPUT_FILE" == "" ] ; then
  $ECHO "git $COMMAND_NAME: you need to specify at least one package or input file."
  $ECHO
  usage $COMMAND_NAME 1
fi

BASH_FULL_VERSION=$((${BASH_VERSINFO[0]} * 10000 + ${BASH_VERSINFO[1]} * 100 + ${BASH_VERSINFO[2]}))
if (( BASH_FULL_VERSION >= 40100 )); then
  # bash 4.1 or newer
  if [ $VERBOSE == 0 ]; then
    # send verbose messages to /dev/null
    exec {verbose}> /dev/null
  else
    # send debug messages to stderr
    exec {verbose}>&2
  fi
  if [ $DEBUG == 0 ]; then
    # send debug messages to /dev/null
    exec {debug}> /dev/null
  else
    # send debug messages to stderr
    exec {debug}>&2
  fi
else
  # bash 4.0 or older
  verbose=11
  if [ $VERBOSE == 0 ]; then
    # send verbose messages to /dev/null
    exec 11> /dev/null
  else
    # send debug messages to stderr
    exec 11>&2
  fi
  debug=12
  if [ $DEBUG == 0 ]; then
    # send debug messages to /dev/null
    exec 12> /dev/null
  else
    # send debug messages to stderr
    exec 12>&2
  fi
fi

if [ "$INPUT_FILE" ]; then
  # check the syntax of the input file
  INVALID=`cat "$INPUT_FILE" | sed -e's|\s*#.*||' | grep -v '^\s*$' | grep -v -E '^/*\w+(/\w+)?/*$' || true`
  if [ -n "$INVALID" ]; then
    $ECHO "Some lines of $INPUT_FILE are not in a valid format:"
    $ECHO "$RED$INVALID$NORMAL"
    exit 1
  fi
  unset INVALID
fi

# initialize the local repository
if [ -z "$CMSSW_BASE" ]; then
  $ECHO "CMSSW environment not setup, please run 'cmsenv' before 'git $COMMAND_NAME'."
  exit 1
fi
if ! [ -d $CMSSW_BASE/src/.git ]; then
  if [ "$COMMAND_NAME" == "cms-rmpkg" ]; then
    $ECHO "git $COMMAND_NAME : nothing to do."
    exit 1
  else
    git cms-init $INITOPTIONS
  fi
fi

cd $CMSSW_BASE/src

case `git --version` in
  git\ version\ 1.7*)
    # git 1.7.x does not support a leading slash in .gitignore and .git/info/sparse-checkout
    LEADING_SLASH=
  ;;
  *)
    LEADING_SLASH=/
  ;;
esac

# check if using a reference repository
if [ "$CMSSW_GIT_REFERENCE" == "" ] && [ -f $CMSSW_BASE/src/.git/objects/info/alternates ]; then
  CMSSW_GIT_REFERENCE=`cat $CMSSW_BASE/src/.git/objects/info/alternates | head -n1`
fi

# if using a personal reference repository, update it from the official one
if [ -e $CMSSW_GIT_REFERENCE/create-`whoami` ]; then
  (cd $CMSSW_GIT_REFERENCE ; git remote update origin >&${verbose} 2>&1)
fi

if [ "$(git status --porcelain --untracked=no | grep '^[ACDMRU]')" ]; then
  $ECHO "${RED}Error:${NORMAL} there are staged but not committed changes on your working tree, please commit or stash them."
  exit 1
fi

CURRENT_BRANCH=`git symbolic-ref --short HEAD`

# check if requested packages are present to be removed
if [ "$COMMAND_NAME" == "cms-rmpkg" ]; then
  CHECK_RETURN=0
  if [ "$INPUT_FILE" ]; then
    checkPkgFile "$INPUT_FILE" "$CURRENT_BRANCH"
  else
    checkPkgList "$PACKAGES" "$CURRENT_BRANCH"
  fi
fi

# create temporary sparse checkout file
if [ "$COMMAND_NAME" == "cms-addpkg" ]; then
  cp -f $CMSSW_BASE/src/.git/info/sparse-checkout $CMSSW_BASE/src/.git/info/sparse-checkout-new
else
  touch $CMSSW_BASE/src/.git/info/sparse-checkout-new
fi

# add the requested package(s) to the temporary file
if [ "$INPUT_FILE" ]; then
  verbose "$ACTION packages"
  verbose "`cat "$INPUT_FILE"`"

  cat "$INPUT_FILE" | sed -e's|\s*#.*||' | grep -v '^\s*$' | sed -e "s|[/]*$|/|;s|^/*|${LEADING_SLASH}|" >> $CMSSW_BASE/src/.git/info/sparse-checkout-new
else
  verbose "$ACTION packages"
  for PKG_NAME in $PACKAGES; do
    verbose $PKG_NAME
  done

  for PKG_NAME in $PACKAGES; do
    echo $PKG_NAME | sed -e "s|[/]*$|/|;s|^/*|${LEADING_SLASH}|" >> $CMSSW_BASE/src/.git/info/sparse-checkout-new
  done
fi

# add or remove from the real sparse checkout file
cat $CMSSW_BASE/src/.git/info/sparse-checkout-new | sort -u > $CMSSW_BASE/src/.git/info/sparse-checkout-new-sorted
if [ "$COMMAND_NAME" == "cms-addpkg" ]; then
  mv $CMSSW_BASE/src/.git/info/sparse-checkout-new-sorted $CMSSW_BASE/src/.git/info/sparse-checkout
  rm -f $CMSSW_BASE/src/.git/info/sparse-checkout-new
else
  grep -v -x -f $CMSSW_BASE/src/.git/info/sparse-checkout-new-sorted $CMSSW_BASE/src/.git/info/sparse-checkout > $CMSSW_BASE/src/.git/info/sparse-checkout-new
  mv $CMSSW_BASE/src/.git/info/sparse-checkout-new $CMSSW_BASE/src/.git/info/sparse-checkout
  rm -f $CMSSW_BASE/src/.git/info/sparse-checkout-new-sorted
fi

# update the working area
git read-tree -mu HEAD

# check if requested packages were successfully added
if [ "$COMMAND_NAME" == "cms-addpkg" ]; then
  if [ "$INPUT_FILE" ]; then
    checkPkgFile "$INPUT_FILE" "$CURRENT_BRANCH"
  else
    checkPkgList "$PACKAGES" "$CURRENT_BRANCH"
  fi
  exit 0
fi
