#! /bin/bash -e

function usage() {
  cat <<@EOF
Usage: git cms-cherry-pick <commit1>[..<commit2>] [--remote <remote>] [<cherry-pick optional arguments>]

Description:
  Cherry pick commit(s), ensuring modified subpackages are added before the commits are applied.
@EOF
  exit $1
}

# mandatory commit(s) to cherry-pick
COMMITS=${1}
[ "$COMMITS" ] || usage 1

# optional remote
REMOTE=""

OPTIONS=()
shift; # start after the commit argument
while [[ $# -gt 0 ]]; do
    case ${1} in
	-h|--help)
	    usage 1
	    ;;
	-r|--remote)
	    REMOTE=${2}
	    shift; shift;
	    ;;
	*)  OPTIONS+=("$1");
	    shift;;
    esac
done

# go to release
[ "$CMSSW_BASE" ] && cd $CMSSW_BASE/src

# add repository where commits to be cherry-picked can be found
if [ -n "${REMOTE}" ]; then
    git cms-remote add ${REMOTE}
    git fetch ${REMOTE}
fi

# download modified subpackages
git diff ${COMMITS} --name-only --no-renames | cut -d/ -f-2 | sort -u | xargs -r git cms-addpkg

# cherry-pick with user arguments
git cherry-pick ${COMMITS} ${OPTIONS[@]}
