#! /bin/bash -e

function usage() {
  cat <<@EOF
Usage: git cms-show-pr <pull request> [<branch>]

Description:
  Cherry pick the commits that are part of a pull request that has been opened or merged 
  in the master branch, or in <branch> if it is specified.
@EOF
  exit $1
}

# the number of the pull request
PULL=$1
[ "$PULL" ] || usage 1

# for a backport, specify the target branch that was used
BRANCH=$2
[ "$BRANCH" ] || BRANCH=master

# FIXME add an option to support alternate repositories ?
REMOTE="official-cmssw"

[ "$CMSSW_BASE" ] && cd $CMSSW_BASE/src

# fetch the master branch from upstream
git fetch -q $REMOTE $BRANCH

# fetch the pull request
git fetch -q $REMOTE pull/$PULL/head

# find the branch point
BRANCH_POINT=$(diff -u <(git rev-list --first-parent FETCH_HEAD) <(git rev-list --first-parent $REMOTE/$BRANCH) | sed -ne 's/^ //p' | head -n1 -)

# show the commits in the pull request
git cherry-pick FETCH_HEAD...$BRANCH_POINT
