.TH GIT_CMS_CHERRY_PICK 1 LOCAL

.SH NAME

git-cms-cherry-pick - CMSSW helper to download modified subpackages before applied commits from a cherry-pick.
Either a single commit or a range of commits can be passed (equivalently branch names), following the standard `git cherry-pick` command.

.SH SYNOPSIS

.B git cms-cherry-pick {<commit1>}[..<commit2>] [options]

.SH OPTIONS

.TP 5

-r, --remote

add the remote containing the commits to be cherry-picked
